### ISSUE TITLE
Email ou Username do GitHub dos alunos

### ISSUE THREAD

**Issue by JoaoCarabetta** [fccoelho/pypixplorer#20]
joao.carabetta@gmail.com

**Comment by claragao** [comment]
claragao
13aclara@gmail.com

**Comment by Wangbarros** [comment]
wangbarros@gmail.com

**Comment by jorgefernandoperezgimenez** [comment]
jf.gimenez@hotmail.com

**Comment by ThiagoTrabach** [comment]
thiago.trabach@gmail.com

**Comment by fernandascovino** [comment]
fscovinom@hotmail.com

**Comment by odanoburu** [comment]
[odanoburu](mail-to:odanoburu@users.noreply.github.com)

**Comment by rafaelmesqs** [comment]
rafaelsmesquita1997@gmail.com

**Comment by brendaprallon** [comment]
brendaprallon

**Comment by bcmresende** [comment]
bcmresende@gmail.com

**Comment by ascupinari** [comment]
amanda.scupinari@gmail.com

**Comment by delsonbarros** [comment]
delsonbarros2@gmail.com

**Comment by blankluke** [comment]
lucaslopesbranco@gmail.com
