### ISSUE TITLE
Write tests for remote module

### ISSUE THREAD

**Issue by fccoelho** [fccoelho/pypixplorer#5]
Reach and maintain 100% coverage in the test module. stub test module has already been created.

**Comment by ThiagoTrabach** [comment]
Some methods haven't been implemented yet:
get_dependencies()
def dependency_graph()
get_popularity()
release_series()
get_by_TROVE_classifier()
get_well_maintained()

Only after they're implemented I'll be able to create tests to evaluate them.

**Comment by fccoelho** [comment]
I am closing this issue because the ideal situation is that authors of the features write their own tests
